### ISSUE TITLE
Unable to export liquids from output tank in chemical laboratory

### ISSUE THREAD

**Issue by Stepan325** [pWn3d1337/Techguns2#105]
I can't get liquids from output tank in chemical laboratory. I have many mods adding tubes and capsules for liquids, but i can't get generated creeper acid.
There are my mods, i don't know what is wrong:
additionalpipes, backpak, bibliocraft, buildcraft, chickenchunks, doomlikedungeons, enchantingplus, forgelin, furnace overhaul, gravitygun, icbmclassic, industrialcraft2, industrialforegoing, inventorytweaks, ironchest, ironman, jei, malisisdoors, nei(addon for jei), obfuscate(?), opencomputers, mmdorespawn, portalgun, optifine, redstoneflux, subcommonsublib, techguns, telepads, teslacore, treechopper, vehiclemodbymrcrayfish, xaeros minimap
I think lwjgl can't find output tank, because chemical laboratory has 2 tanks. Please help me, say what mods i haven,t or what is breaking techguns logic.

**Comment by pWn3d1337** [comment]
You need a pipe that has an "extract" mode. For example Mekanism and EnderIO pipes can be configured for that. Thermal Pipes need a Servo. 

In your mod buildcraft should work when you use an extraction pipe.

**Comment by Stepan325** [comment]
I used wooden and emerald pipes, but it's locked and wrench is not helping...

**Comment by Stepan325** [comment]
![image](https://user-images.githubusercontent.com/48287791/53898586-6acb2800-4049-11e9-8e01-e93dc6651e0f.png)
This is construction to get any liquids fo reaction chamber, but i can't extract anything from chemical laboratory
![image](https://user-images.githubusercontent.com/48287791/53898696-a36b0180-4049-11e9-8738-05bed1f1f61e.png)
I think something wrong in options of laboratory, or reaction chamber isn't sending request for acid

**Comment by Stepan325** [comment]
I don't know, maybe it's config?

**Comment by pWn3d1337** [comment]
The machines work fine, your piping is wrong. Techguns machines do not put out the liquid into pipes, but requires pipes that extract the liquid from the machine. This allows to not need any side configuration in the machine and you can extract from any side. I have not used buildcraft in 1.12 but in earlier versions an extraction pipe needed power. A redstone engine was enough.

Mekansim and EnderIO pipes work well as they can be configured to extract. Thermal pipes work well too, you just need to add a servo.

immersive engineering / buildcraft pipes don't work that well because you need a pump/extraction pipe. which is more annoying to setup.

**Comment by Stepan325** [comment]
Thank you very much! You was right about energy, pipes need it to work, but from pump to chemical laboratory it's not... Чудеса да и только! - This is russian "Miracles and more!"

**Comment by Stepan325** [comment]
I found an answer. You have to turn off "machines not need energy" in mod config.
