### ISSUE TITLE
Config to disable Techguns Inventory

### ISSUE THREAD

**Issue by dariusfontan** [pWn3d1337/Techguns2#108]
Would it be possible to add a config that disables the custom inventory added by Techguns ?
Or a simple option to just hide it ?
I really like many aspects this mod adds, but I don't want to implement all of them in my modpack,
especially not the additional inventory, and I don't want to confuse players of my modpack with it,
when it's not intended to be used.
Or could I disable it on my end through CraftTweaker or something ?
Thanks!

**Comment by pWn3d1337** [comment]
The Techguns inventory is an important part of the mod as it also contains toggle buttons to disable jetpack etc. without keybinds. Adding an option to disable it is not a trivial task because many methods are coded to use the inventory (like putting empty magazines into the ammo inventory first).

Adding modularity to the mod is a lot of work, in this case it will not be added.
