### ISSUE TITLE
Cascading world gen lag

### ISSUE THREAD

**Issue by kohlth** [pWn3d1337/Techguns2#147]
hello i used tech guns in a pack of mine on a server i  have had remove the mod because it keeps loading chunks to generates structures and makes the world generally unplayable, i have tried to turn down the structure spawn rate but it does not seem to work 

[04:28:34] [Server thread/WARN] [FML]: Techguns loaded a new chunk [65, 64] in dimension 0 (overworld) while populating chunk [64, 64], causing cascading worldgen lag.

**Comment by kohlth** [comment]
(latest beta version 1.12.2)

**Comment by pWn3d1337** [comment]
The way of spawning structures is intended. Structures that are greater than a chunk need to generate more than 1 chunk at once. If you use default settings for structure spawning this should be no problem at all. Looks like weak server hardware to me.

**Comment by kohlth** [comment]
i have turned structure spawning to 0 and it still loaded chunks too

**Comment by Inrixia** [comment]
@pWn3d1337 Running on a 6700k at 4.2Ghz with 12GB ram allocated and still getting the issues so doubt its a "Weak Server Hardware" Issue. I understand that structures need to generate entirely but the fact that it will make a server near unplayable during gen is a bit excessive.

**Comment by TerdyTheTerd** [comment]
Run a JVM profiler and show that its TG thats actually eating up CPU time, otherwise its likely due to too many mods, and TG is getting blamed because its the only spitting something into the console. Pre-gens are always highly advised as chunk generation can considerably hang the main server thread.

**Comment by darthvader45** [comment]
Weirdly enough, I had this happen in singleplayer as well.  Only running like 40-ish mods, so it's not the too many mods problem.

**Comment by pWn3d1337** [comment]
A large structure creates a few chunks at once, but that should not be too much of a problem, a small lag can happen depending on server power. A real cascade where one generation triggers the next and so on should not happen because buildings spawns are arranged at a regular grid at the config file disallows you to set building spawns to every chunk.
