### ISSUE TITLE
4 bugs found in the mod

### ISSUE THREAD

**Issue by Yoga34** [pWn3d1337/Techguns2#221]
Greetings. I have long wanted to contact the developer of this mod, but nothing worked for me. Only now I could. I want to report four bugs I found in the mod. The video is attached.

1. Bug with the armor stand. The Power and Steam Armor helmet always faces to the right of itself, regardless of how the player stances.
2. Bug with mittens. If you take some kind of weapon in your hands, then the mittens are not attached to the hands, but hang on the sides as if they were pockets.
https://youtu.be/XCloY4dsRC0

3. Bug with connecting wires from other mods.
4. New turret from Galacticraft mod shoots at a turret from your mod, considering it a hostile mob.
https://youtu.be/GgkeAMJoppM

End of message.

**Comment by pWn3d1337** [comment]
1) The helmet orientation seems strange, sure you didn't just click the wrong side? I never had this problem.

2) Caused by other mods when they want to change player animations.

3) That's no bug, IC2 uses a different Power system. Techguns machines only accept FE compatible cables. (Most tech mods use RF or FE, but not all). You can try some kind of power converter, as far as I recall Mekanism cables can convert from IC2 power to RF.

4) What a GC turret sees as enemy or not is GC's decision not Techguns.

**Comment by Yoga34** [comment]
4, ok i will then tell the GC command
