### ISSUE TITLE
Do ore clusters spawn randomly anymore?

### ISSUE THREAD

**Issue by Mooshroom8** [pWn3d1337/Techguns2#266]
So there used to be a tracker, but using JEI I can't find it. Do they just spawn in structures now? This is preventing me from finding any clusters since I can't find many structures. [Also is there a easier way to find structures?] I don't want to mess with config either.

**Comment by pWn3d1337** [comment]
Cluster spawn in structures only in 1.12 by default. There is the possibility to add them do natural ore spawn by using a mod like cofh world, but you have to do that yourself.

Structures are spawned along a grid depending on spawn weights, by default this is 16, 32 and 64 chunks, a chunk is 16x16 blocks, so that means at coordinates like 256,256, or 256,0, 256,-256 there will be a small structure if the terrain is flat enough.

at 1024,1024 ; 1024,-1024; 0,1024 ... and so on there could be large buildings. Same with 2048 and so on. Medium structures will be at 512, 1536 (1024+512, at 1024 there will be a large)

**Comment by Mooshroom8** [comment]
Thanks!
